### ISSUE TITLE
Handle ICAT unavailability better than just showing a 500 error

### ISSUE THREAD

**Issue by dtasev** [autoreduction/queue-processor#939]
Issue raised by: [developer/user/project requirement]

### What?
Currently we just fail with a 500 error - instead perhaps we should show "ICAT service unavailable"?

This can cover other services as well, if possible

In logs it can be found for 23/Nov in `Autoreduction/WebApp/autoreduce_webapp/autoreduction.log`

<details>
<summary>
Full error log - fails in `icat_cache.py`
</summary>

[23/Nov/2020 10:38:32] ERROR [django.request:228] Internal Server Error: /
Traceback (most recent call last):
  File "c:\python37\lib\urllib\request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\python37\lib\http\client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python37\lib\http\client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\python37\lib\http\client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\python37\lib\http\client.py", line 1028, in _send_output
    self.send(msg)
  File "c:\python37\lib\http\client.py", line 968, in send
    self.connect()
  File "c:\python37\lib\http\client.py", line 1424, in connect
    super().connect()
  File "c:\python37\lib\http\client.py", line 940, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\python37\lib\socket.py", line 728, in create_connection
    raise err
  File "c:\python37\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Autoreduction\WebApp\autoreduce_webapp\autoreduce_webapp\icat_cache.py", line 54, in open_icat
    self.icat = ICATCommunication(**self.kwargs)
  File "C:\Autoreduction\WebApp\autoreduce_webapp\autoreduce_webapp\icat_communication.py", line 48, in __init__
    self.client = icat.Client(url=kwargs['URL'])
  File "c:\python37\lib\site-packages\icat\client.py", line 141, in __init__
    super(Client, self).__init__(self.url, **kwargs)
  File "c:\python37\lib\site-packages\suds\client.py", line 111, in __init__
    self.wsdl = reader.open(url)
  File "c:\python37\lib\site-packages\suds\reader.py", line 151, in open
    d = self.fn(url, self.options)
  File "c:\python37\lib\site-packages\suds\wsdl.py", line 135, in __init__
    d = reader.open(url)
  File "c:\python37\lib\site-packages\suds\reader.py", line 78, in open
    d = self.download(url)
  File "c:\python37\lib\site-packages\suds\reader.py", line 94, in download
    fp = self.options.transport.open(Request(url))
  File "c:\python37\lib\site-packages\suds\transport\http.py", line 63, in open
    return self.u2open(u2request)
  File "c:\python37\lib\site-packages\suds\transport\http.py", line 119, in u2open
    return url.open(u2request, timeout=tm)
  File "c:\python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "c:\python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "c:\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\python37\lib\urllib\request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\python37\lib\urllib\request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Autoreduction\WebApp\autoreduce_webapp\reduction_viewer\view_utils.py", line 39, in request_processor
    return func(request, *args, **kws)
  File "C:\Autoreduction\WebApp\autoreduce_webapp\reduction_viewer\views.py", line 73, in index
    user = authenticate(token=request.GET.get('sessionid'))
  File "c:\python37\lib\site-packages\django\contrib\auth\__init__.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Autoreduction\WebApp\autoreduce_webapp\autoreduce_webapp\backends.py", line 49, in authenticate
    user.is_superuser = icat.is_admin(int(person['usernumber']))
  File "C:\Autoreduction\WebApp\autoreduce_webapp\autoreduce_webapp\icat_cache.py", line 185, in member_func
    new_obj = self.check_cache(obj_type, obj_id)
  File "C:\Autoreduction\WebApp\autoreduce_webapp\autoreduce_webapp\icat_cache.py", line 118, in check_cache
    ret_obj = self.update_cache(obj_type, obj_id)
  File "C:\Autoreduction\WebApp\autoreduce_webapp\autoreduce_webapp\icat_cache.py", line 84, in update_cache
    self.()open_icat  # Open an ICAT session if we don't have one open.
  File "C:\Autoreduction\WebApp\autoreduce_webapp\autoreduce_webapp\icat_cache.py", line 57, in open_icat
    LOGGER.error("Failed to connect to ICAT: %s - %s", type(excep).__name, excep)
AttributeError: type object 'URLError' has no attribute '_ICATCache__name'

</details>

### How to test the issue is resolved
I guess - mock an offline ICAT or change the URL and see that the failure shows the correct error

**Comment by dtasev** [comment]
Was this fixed? I remember @rickybassom you worked towards making the error a bit friendlier

**Comment by rickybassom** [comment]
Not yet, it got buried in my todo list a bit. Shouldn't be too much work though.

**Comment by dtasev** [comment]
Will you have a chance to have a look in this sprit @rickybassom ? If not we'll probably come back to this after the start of the cycle
